namespace ODK.Services.Security;

public enum ChapterAdminSecurable
{
    None,
    AdminMembers,
    Any,
    Branding,
    BulkEmail,
    ContactMessages,
    Conversations,
    Emails,
    Events,
    EventSettings,
    Location,
    MemberAdmin,
    MemberApprovals,
    MemberEventResponses,
    MemberExport,
    Members,
    MembershipSettings,
    Pages,
    PaymentAccount,
    Payments,
    PaymentSettings,
    PrivacySettings,
    Properties,
    Publish,
    Questions,
    SiteSubscription,
    SocialMedia,
    Subscriptions,
    Texts,
    Topics,
    Venues
}