using System;
using System.Data;
using System.Data.SqlClient;

namespace ODK.Data.Sql
{
    public class SqlColumn
    {
        public SqlColumn(string name)
        {
            SetColumnName(name);
        }

        public bool AutoGenerated => Identity;

        public string ColumnName { get; private set; }

        public bool Identity { get; private set; }

        public string ParameterName { get; private set; }

        public string TableName { get; private set; }

        public SqlDbType Type { get; private set; }

        private string SqlName { get; set; }

        public SqlColumn FromTable(string tableName)
        {
            TableName = tableName;
            SetSqlName();
            return this;
        }

        public SqlColumn HasColumnName(string columnName)
        {
            SetColumnName(columnName);
            return this;
        }

        public SqlColumn HasColumnType(SqlDbType type)
        {
            Type = type;
            return this;
        }

        public SqlColumn IsIdentity()
        {
            Identity = true;
            return this;
        }

        public IDataParameter ToParameter(object value)
        {
            return new SqlParameter(ParameterName, Type) { Value = value ?? DBNull.Value };
        }

        public string ToSql()
        {
            return SqlName;
        }

        private void SetColumnName(string columnName)
        {
            ColumnName = columnName;
            ParameterName = $"@{columnName}";

            SetSqlName();
        }

        private void SetSqlName()
        {
            SqlName = (!string.IsNullOrEmpty(TableName) ? $"{TableName}." : "") + $"[{ColumnName}]";
        }
    }
}
