<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ODK.Core\ODK.Core.csproj" />
    <ProjectReference Include="..\ODK.Core.Workflows\ODK.Core.Workflows.csproj" />
    <ProjectReference Include="..\ODK.Data.Core\ODK.Data.Core.csproj" />
    <ProjectReference Include="..\ODK.Resources\ODK.Resources.csproj" />
  </ItemGroup>

</Project>
