//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODK.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODK.Resources.Resources.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simpler, fairer platform for running groups and events - without high recurring fees or platform lock-in..
        /// </summary>
        public static string ASimplerFairerPlatformForRunningGroupsAndEvents {
            get {
                return ResourceManager.GetString("ASimplerFairerPlatformForRunningGroupsAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your community.
        /// </summary>
        public static string BuildYourCommunity {
            get {
                return ResourceManager.GetString("BuildYourCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in notifications.
        /// </summary>
        public static string BuiltInNotifications {
            get {
                return ResourceManager.GetString("BuiltInNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built with organisers in mind.
        /// </summary>
        public static string BuiltWithOrganisersInMind {
            get {
                return ResourceManager.GetString("BuiltWithOrganisersInMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities grow best when organisers aren’t stressed about monthly bills..
        /// </summary>
        public static string CommunitiesGrowBestWhenOrganisersArentStressedAboutMonthlyBills {
            get {
                return ResourceManager.GetString("CommunitiesGrowBestWhenOrganisersArentStressedAboutMonthlyBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities shouldn’t feel like subscriptions..
        /// </summary>
        public static string CommunitiesShouldntFeelLikeSubscriptions {
            get {
                return ResourceManager.GetString("CommunitiesShouldntFeelLikeSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control over your members.
        /// </summary>
        public static string ControlOverYourMembers {
            get {
                return ResourceManager.GetString("ControlOverYourMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and manage groups.
        /// </summary>
        public static string CreateAndManageGroups {
            get {
                return ResourceManager.GetString("CreateAndManageGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed for organisers.
        /// </summary>
        public static string DesignedForOrganisers {
            get {
                return ResourceManager.GetString("DesignedForOrganisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair pricing. No surprises..
        /// </summary>
        public static string FairPricingNoSurprises {
            get {
                return ResourceManager.GetString("FairPricingNoSurprises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiar group and event structures.
        /// </summary>
        public static string FamiliarGroupAndEventStructures {
            get {
                return ResourceManager.GetString("FamiliarGroupAndEventStructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible privacy controls.
        /// </summary>
        public static string FlexiblePrivacyControls {
            get {
                return ResourceManager.GetString("FlexiblePrivacyControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How members interact.
        /// </summary>
        public static string HowMembersInteract {
            get {
                return ResourceManager.GetString("HowMembersInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How we enable you.
        /// </summary>
        public static string HowWeEnableYou {
            get {
                return ResourceManager.GetString("HowWeEnableYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member roles and approvals.
        /// </summary>
        public static string MemberRolesAndApprovals {
            get {
                return ResourceManager.GetString("MemberRolesAndApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving from another platform?.
        /// </summary>
        public static string MovingFromAnotherPlatform {
            get {
                return ResourceManager.GetString("MovingFromAnotherPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bloated features. No confusing upgrades. Just solid infrastructure for real communities..
        /// </summary>
        public static string NoBloatedFeatures {
            get {
                return ResourceManager.GetString("NoBloatedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our goal is simple: make the platform sustainable to support your community..
        /// </summary>
        public static string OurGoalIsSimple {
            get {
                return ResourceManager.GetString("OurGoalIsSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment portal.
        /// </summary>
        public static string PaymentPortal {
            get {
                return ResourceManager.GetString("PaymentPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running a local group, club, or meetup should be rewarding - not expensive or complicated..
        /// </summary>
        public static string RunningALocalGroupShouldBeRewarding {
            get {
                return ResourceManager.GetString("RunningALocalGroupShouldBeRewarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule events with RSVP limits and waitlists.
        /// </summary>
        public static string ScheduleEvents {
            get {
                return ResourceManager.GetString("ScheduleEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple onboarding for existing members.
        /// </summary>
        public static string SimpleOnboardingForExistingMembers {
            get {
                return ResourceManager.GetString("SimpleOnboardingForExistingMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple tools that just work.
        /// </summary>
        public static string SimpleToolsThatJustWork {
            get {
                return ResourceManager.GetString("SimpleToolsThatJustWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching platforms shouldn’t mean starting over..
        /// </summary>
        public static string SwitchingPlatformsShouldntMeanStartingOver {
            get {
                return ResourceManager.GetString("SwitchingPlatformsShouldntMeanStartingOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problem.
        /// </summary>
        public static string TheProblem {
            get {
                return ResourceManager.GetString("TheProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many organisers feel priced out, boxed in, or dependent on platforms that don’t prioritise their community..
        /// </summary>
        public static string TooManyOrganisersFeelPricedOut {
            get {
                return ResourceManager.GetString("TooManyOrganisersFeelPricedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent pricing.
        /// </summary>
        public static string TransparentPricing {
            get {
                return ResourceManager.GetString("TransparentPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We support.
        /// </summary>
        public static string WeSupport {
            get {
                return ResourceManager.GetString("WeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can respond.
        /// </summary>
        public static string WhoCanRespond {
            get {
                return ResourceManager.GetString("WhoCanRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can see events.
        /// </summary>
        public static string WhoCanSeeEvents {
            get {
                return ResourceManager.GetString("WhoCanSeeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can see venues.
        /// </summary>
        public static string WhoCanSeeVenues {
            get {
                return ResourceManager.GetString("WhoCanSeeVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You control.
        /// </summary>
        public static string YouControl {
            get {
                return ResourceManager.GetString("YouControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether your group is public, private, paid, free, or somewhere in between - you decide how it runs..
        /// </summary>
        public static string YouDecideHowYourGroupRuns {
            get {
                return ResourceManager.GetString("YouDecideHowYourGroupRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your community comes with you..
        /// </summary>
        public static string YourCommunityComesWithYou {
            get {
                return ResourceManager.GetString("YourCommunityComesWithYou", resourceCulture);
            }
        }
    }
}
