//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODK.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODK.Resources.Resources.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A better home for your community..
        /// </summary>
        public static string ABetterHomeForYourCommunity {
            get {
                return ResourceManager.GetString("ABetterHomeForYourCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add co-organisers and give them access to the parts of the group they actually need - whether that’s organising events, managing members or helping run the community..
        /// </summary>
        public static string AddCoOrganisers {
            get {
                return ResourceManager.GetString("AddCoOrganisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have a community? Bring it with you..
        /// </summary>
        public static string AlreadyHaveACommunityBringItWithYou {
            get {
                return ResourceManager.GetString("AlreadyHaveACommunityBringItWithYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities shouldn’t feel like subscriptions..
        /// </summary>
        public static string CommunitiesShouldntFeelLikeSubscriptions {
            get {
                return ResourceManager.GetString("CommunitiesShouldntFeelLikeSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your organisers.
        /// </summary>
        public static string ContactYourOrganisers {
            get {
                return ResourceManager.GetString("ContactYourOrganisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control who can:.
        /// </summary>
        public static string ControlWhoCan {
            get {
                return ResourceManager.GetString("ControlWhoCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every group is different. You decide how yours works..
        /// </summary>
        public static string EveryGroupIsDifferent {
            get {
                return ResourceManager.GetString("EveryGroupIsDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to run your group..
        /// </summary>
        public static string EverythingYouNeedToRunYourGroup {
            get {
                return ResourceManager.GetString("EverythingYouNeedToRunYourGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair pricing. Useful tools. No unnecessary complexity..
        /// </summary>
        public static string FairPricingUsefulToolsNoUnnecessaryComplexity {
            get {
                return ResourceManager.GetString("FairPricingUsefulToolsNoUnnecessaryComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string FeatureEvents {
            get {
                return ResourceManager.GetString("FeatureEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule events, manage RSVPs, set attendance limits and automatically handle waitlists..
        /// </summary>
        public static string FeatureEventsDescription {
            get {
                return ResourceManager.GetString("FeatureEventsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string FeatureGroups {
            get {
                return ResourceManager.GetString("FeatureGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your group, manage membership and decide how it works..
        /// </summary>
        public static string FeatureGroupsDescription {
            get {
                return ResourceManager.GetString("FeatureGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string FeatureMembers {
            get {
                return ResourceManager.GetString("FeatureMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve members, manage organisers and keep track of who’s part of your community..
        /// </summary>
        public static string FeatureMembersDescription {
            get {
                return ResourceManager.GetString("FeatureMembersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string FeatureNotifications {
            get {
                return ResourceManager.GetString("FeatureNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep members informed about events, memberships and important group activity..
        /// </summary>
        public static string FeatureNotificationsDescription {
            get {
                return ResourceManager.GetString("FeatureNotificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string FeaturePayments {
            get {
                return ResourceManager.GetString("FeaturePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge for memberships or events and manage payments from one place..
        /// </summary>
        public static string FeaturePaymentsDescription {
            get {
                return ResourceManager.GetString("FeaturePaymentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free to get started. No credit card required..
        /// </summary>
        public static string FreeToGetStartedNoCreditCardRequired {
            get {
                return ResourceManager.GetString("FreeToGetStartedNoCreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give organisers the access they need without giving everyone access to everything..
        /// </summary>
        public static string GiveOrganisersTheAccessTheyNeed {
            get {
                return ResourceManager.GetString("GiveOrganisersTheAccessTheyNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your organisers the right access..
        /// </summary>
        public static string GiveYourOrganisersTheRightAccess {
            get {
                return ResourceManager.GetString("GiveYourOrganisersTheRightAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import your existing members and move your group into a familiar group-and-event structure. Your members can then join you on {0} without you having to start from zero..
        /// </summary>
        public static string ImportYourExistingMembers {
            get {
                return ResourceManager.GetString("ImportYourExistingMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join your group.
        /// </summary>
        public static string JoinYourGroup {
            get {
                return ResourceManager.GetString("JoinYourGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep sensitive member and payment information restricted to the people who need it..
        /// </summary>
        public static string KeepSensitiveInformationRestricted {
            get {
                return ResourceManager.GetString("KeepSensitiveInformationRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your members, events and communication in one place. {0} gives you the essentials for running a real-world community - without making you manage a complicated platform..
        /// </summary>
        public static string KeepYourMembersEventsAndCommunicationInOnePlace {
            get {
                return ResourceManager.GetString("KeepYourMembersEventsAndCommunicationInOnePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And because each group controls its own privacy settings, members only see what your group chooses to share..
        /// </summary>
        public static string MembersOnlySeeWhatYourGroupChoosesToShare {
            get {
                return ResourceManager.GetString("MembersOnlySeeWhatYourGroupChoosesToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No high recurring fees. No platform lock-in..
        /// </summary>
        public static string NoHighRecurringFeesNoPlatformLockIn {
            get {
                return ResourceManager.GetString("NoHighRecurringFeesNoPlatformLockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rebuilding your member list. No starting over..
        /// </summary>
        public static string NoRebuildingYourMemberListNoStartingOver {
            get {
                return ResourceManager.GetString("NoRebuildingYourMemberListNoStartingOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to run your community your way?.
        /// </summary>
        public static string ReadyToRunYourCommunityYourWay {
            get {
                return ResourceManager.GetString("ReadyToRunYourCommunityYourWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond to events.
        /// </summary>
        public static string RespondToEvents {
            get {
                return ResourceManager.GetString("RespondToEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run your groups, events and memberships in one place - with the tools you need, fair pricing, and control over your community..
        /// </summary>
        public static string RunYourGroupsEventsAndMembershipsInOnePlace {
            get {
                return ResourceManager.GetString("RunYourGroupsEventsAndMembershipsInOnePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running a community rarely means doing everything yourself..
        /// </summary>
        public static string RunningACommunityRarelyMeansDoingEverythingYourself {
            get {
                return ResourceManager.GetString("RunningACommunityRarelyMeansDoingEverythingYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See event venues.
        /// </summary>
        public static string SeeEventVenues {
            get {
                return ResourceManager.GetString("SeeEventVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See member information.
        /// </summary>
        public static string SeeMemberInformation {
            get {
                return ResourceManager.GetString("SeeMemberInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your events.
        /// </summary>
        public static string SeeYourEvents {
            get {
                return ResourceManager.GetString("SeeYourEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple for your members..
        /// </summary>
        public static string SimpleForYourMembers {
            get {
                return ResourceManager.GetString("SimpleForYourMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new group or bring an existing one with you..
        /// </summary>
        public static string StartANewGroupOrBringAnExistingOneWithYou {
            get {
                return ResourceManager.GetString("StartANewGroupOrBringAnExistingOneWithYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start for free. Upgrade when your community needs more..
        /// </summary>
        public static string StartForFreeUpgradeWhenYourCommunityNeedsMore {
            get {
                return ResourceManager.GetString("StartForFreeUpgradeWhenYourCommunityNeedsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straightforward pricing..
        /// </summary>
        public static string StraightforwardPricing {
            get {
                return ResourceManager.GetString("StraightforwardPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They get a clear group page, upcoming events, simple RSVPs, waitlists and the information they need - all in one place..
        /// </summary>
        public static string TheyGetAClearGroupPage {
            get {
                return ResourceManager.GetString("TheyGetAClearGroupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We built {0} because running a community shouldn’t mean paying more and more just to keep the tools you’ve always used..
        /// </summary>
        public static string WeBuiltThisPlatformBecause {
            get {
                return ResourceManager.GetString("WeBuiltThisPlatformBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} provides the infrastructure. You run the community..
        /// </summary>
        public static string WeProvideTheInfrastructureYouRunTheCommunity {
            get {
                return ResourceManager.GetString("WeProvideTheInfrastructureYouRunTheCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You run the community. The platform just gives you the tools..
        /// </summary>
        public static string YouRunTheCommunity {
            get {
                return ResourceManager.GetString("YouRunTheCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should be able to run your group, understand what you’re paying for, control your members’ experience and know that your community isn’t locked into a platform..
        /// </summary>
        public static string YouShouldBeAbleToRunYourGroup {
            get {
                return ResourceManager.GetString("YouShouldBeAbleToRunYourGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You shouldn’t have to rebuild your community from scratch just because you change platforms..
        /// </summary>
        public static string YouShouldntHaveToRebuildYourCommunityFromScratch {
            get {
                return ResourceManager.GetString("YouShouldntHaveToRebuildYourCommunityFromScratch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your community. Your rules..
        /// </summary>
        public static string YourCommunityYourRules {
            get {
                return ResourceManager.GetString("YourCommunityYourRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your members, events and group information are managed through your account, with privacy controls that let you decide what is visible and who can access it..
        /// </summary>
        public static string YourMembersEventsAndGroupInformationAreManagedThroughYourAccount {
            get {
                return ResourceManager.GetString("YourMembersEventsAndGroupInformationAreManagedThroughYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your members shouldn’t need to learn a complicated platform just to come to an event..
        /// </summary>
        public static string YourMembersShouldntNeedToLearnAComplicatedPlatform {
            get {
                return ResourceManager.GetString("YourMembersShouldntNeedToLearnAComplicatedPlatform", resourceCulture);
            }
        }
    }
}
